### ISSUE TITLE
Not compatible with tslint 5.9.1

### ISSUE THREAD

**Issue by KurtPreston** [ThaNarie/tslint-teamcity-reporter#4]
Hey, thanks for your project!  The module was working great with tslint 5.8.0, but it started throwing errors when I upgraded to tslint 5.9.1:

```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at loadFormatter (/myproject/node_modules/tslint/lib/formatterLoader.js:53:43)
    at Object.findFormatter (/myproject/node_modules/tslint/lib/formatterLoader.js:38:25)
    at Linter.getResult (/myproject/node_modules/tslint/lib/linter.js:121:43)
    at /myproject/node_modules/gulp-tslint/index.js:103:30
    at wrappedMapper (/myproject/node_modules/gulp-tslint/node_modules/map-stream/index.js:83:19)
    at Stream.stream.write (/myproject/node_modules/gulp-tslint/node_modules/map-stream/index.js:95:21)
  ...
```

**Comment by ThaNarie** [comment]
Hi @KurtPreston, It looks like the error is coming from tslint itself.

Could you maybe check what the values for `directory` and `name` are in this line:
`const formatterPath = path.resolve(path.join(directory, name));`
in `/myproject/node_modules/tslint/lib/formatterLoader.js:53:43`

If the first is `null`, it might be that the `--formatters-dir` is not passed correctly, or at all. Could you let me know how you call/configured this reporter? Thanks!

**Comment by KurtPreston** [comment]
Ah, yeah, with 5.9.1, I now have to specify the `formattersDirectory`, otherwise it errors.  I've updated my code and it works now with the following task

My gulp task looks like:
```javascript
gulp.task('tslint', () => {
  const tsconfigPath = paths.projectRoot + '/src/client/tsconfig.json';
  const program = tslint.Linter.createProgram(tsconfigPath);

  return gulp
    .src([
      'src/client/**/*.ts',
      'src/client/**/*.tsx'
    ], {follow: true})
    .pipe(gulpTslint({
      program: program,
      /********* I was previously missing this line ***********/
      formattersDirectory: `${paths.projectRoot}/node_modules/tslint-teamcity-reporter/`,
      formatter: 'tslint-teamcity-reporter'
    }))
    .pipe(gulpTslint.report({
      summarizeFailureOutput: true,
      allowWarnings: true
    }));
```

Thanks for the prompt reply!
